### ISSUE TITLE
[Proposal] Крюк всем, крюк народу!

### ISSUE THREAD

**Issue by Aezukla** [ThetaStation/ThetaStation-Public#20]
### Описание

Сейчас крюк присутствует только на **Skipjack-е** и то в ограниченном количестве (_три штуки_). Добавить его за ТК в аплинк за 10-20 ТК, ибо является улучшенной версией джетпака за 2 ТК. Вооот. И я знаю что вы об этом знаете, но я просто оставлю вот это вот здесь.

**Comment by KIBORG04** [comment]
Добавлен в аплинк
