### ISSUE TITLE
Камера поворачивается, когда не должна.

### ISSUE THREAD

**Issue by aesdfxcgvbh** [ThetaStation/ThetaStation-Public#23]
### Описание

Когда я выхожу из шаттла, камера все еще поворачивается вместе с шаттлом, хотя я уже вышел с того грида. Очень раздражает.
Дискорд - kurw#3443
### Этап воспроизведения

1. Попасть на шаттл своей команды
2. Выйти с шаттла своей команды в космос
3. Повернуть шаттл

**Comment by IlinMihail** [comment]
неактуально
