### ISSUE TITLE
[Proposal] Твикнуть Отображение Таймера Схронов

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation-Public#7]
### Описание

![image](https://github.com/ThetaStation/ThetaStation-Public/assets/17705613/02b1155c-3935-4d0f-8c6d-0595b8a5ea23)

Вот так сейчас выглядит схрон с таймером.

Я бы предложил сделать чтобы цвет таймера был таким же как цвет схрона, и с текущим расположением это сделало бы его незаметным и сливающимся

Поэтому в добавок к изменению цвета, я думаю стоит сделать чтобы таймер отображался над или под схроном, как к примеру имя.

**Comment by IlinMihail** [comment]
неактуально
